### ISSUE TITLE
Requirements.txt is missing

### ISSUE THREAD

**Issue by mikraus94** [peppelinux/django-oidc-op#14]
![image](https://user-images.githubusercontent.com/23478332/143277990-68450191-a628-4ce4-86d6-b6286c245460.png)

```
Collecting oidc-provider==2.0.1
  Using cached oidc_provider-2.0.1.tar.gz (2.5 MB)
  Preparing metadata (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /code/sso/venv/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-t2hfbzxn/oidc-provider_28d08b87c4904370ac8843fa29f9f975/setup.py'"'"'; __file__='"'"'/tmp/pip-install-t2hfbzxn/oidc-provider_28d08b87c4904370ac8843fa29f9f975/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-89umicwx
       cwd: /tmp/pip-install-t2hfbzxn/oidc-provider_28d08b87c4904370ac8843fa29f9f975/
  Complete output (5 lines):
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-install-t2hfbzxn/oidc-provider_28d08b87c4904370ac8843fa29f9f975/setup.py", line 15, in <module>
      with open(os.path.join(os.path.dirname(__file__), 'requirements.txt')) as requirements:
  FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-install-t2hfbzxn/oidc-provider_28d08b87c4904370ac8843fa29f9f975/requirements.txt'
  ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/db/9c/afb07b3c13621dbe3b387cb986e47bdb47e386737d67fb59d75d57019aa8/oidc_provider-2.0.1.tar.gz#sha256=1dd48d3b533adbfc847a914589984175b30a54f87aee6a11a6d84abe05fed9bc (from https://pypi.org/simple/oidc-provider/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Could not find a version that satisfies the requirement oidc-provider==2.0.1 (from versions: 2.0.0, 2.0.1)
ERROR: No matching distribution found for oidc-provider==2.0.1

```

**Comment by peppelinux** [comment]
ciao @mikraus94 

I just fixed the setup file.
the implementation of oidcop went ahead in this project, that's an IAM proxy:
https://github.com/UniversitaDellaCalabria/SATOSA-oidcop

I'd like to rewrite the entire storage system and aling django-oidc-op to the approach I made in satosa-oidcop
Are you interested to get in?

**Comment by peppelinux** [comment]
anyway, you can run again `pip install oidc_provider` to get it working

closed by https://github.com/peppelinux/django-oidc-op/commit/f0370a95d3cee98a1b1461ea54fe1a2ec43f733f
